### ISSUE TITLE
Stephanie - June 2019

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#105]
### Field Work
- [ ] Finish elevating GCREW power lines (good job for L/M)
- [x] Two rounds of CO2 and CH4 measurements, hopefully early in week 1 and late in week 2 (will be re-measuring offsets the first time)
- [x] Maybe due at least one with trailing Norbert
- [x] June litter collection
- [ ] Sort rest of litter
- [x] Finish updating LS inventory data
- [x] Change batteries at Canoe Shed / North Branch
- [x] Reflag collars at Canoe Shed
- [x] Meeting with Nanette and Edward from WVU June 12th
- [ ] Repaint/replace plot stakes

### Coding
- [x] ~Fix real-time data~. BBL screwed this up -> #89 
- [x] Script to handle litter data
- [ ] We have some cleanup work to do on main repo script I think

### Mentoring Lillie #98 
- [x] Work with BBL on R 'syllabus'
- [x] Work with LH and BBL on SLA sampling, measurement

### Other
- [x] PREMIS review meeting is July 10-12. We need to put together summaries, poster, etc.

**Comment by bpbond** [comment]
Thinking about our meeting today:

- [ ] ah 💩 the PREMIS meeting poster is due today
- [ ] commit Friday files; go over editing the 7810 files
- [ ] prep for Lillie sampling W-R-F
- [ ] thinking ahead to #93 - start reading one paper a week, @stephpenn1 to assign?
- [ ] understand litter figure code
- [ ] what is Lillie doing this week, before her sampling? Should we assign her something extra? E.g. read several SLA papers, focusing on methods and anything we might have forgotten

**Comment by bpbond** [comment]
@stephpenn1 A paper to read for next week! https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-3040.2005.01478.x

**Comment by stephpenn1** [comment]
- [ ] Add stormsurge inventory to `PNNL-PREMIS/PREMIS-seawater`
