### ISSUE TITLE
Multi-year inventory data

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#106]
Right now the inventory data is stored a fieldwork-convenient 'wide' form that's not
great for subsequent processing. Need to change this, and change the proximity report that depends on it. 

Something like this:

```r
  inventory_data = inventory_data_raw %>% 
    select(-`Date-2018`, -`Date-2019`) %>%  
    gather(Label, Value, matches("-[0-9]{4}$")) %>% 
    separate(Label, into = c("Variable", "Year"), sep = "-") %>% 
    spread(Variable, Value)
```

**Comment by stephpenn1** [comment]
Lillie, the function to change can be found in `inventory.R`. This function combines inventory data, species codes, and plot data. We would like to transform the inventory into long format before joining. @bpbond is this what you had in mind?

**Comment by bpbond** [comment]
Right.

**Comment by stephpenn1** [comment]
Note: `inventory.R` is updated and working, though it currently doesn't work when ran through `drake.R`
