### ISSUE TITLE
2019-08-06 planning meeting - agenda and notes

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#113]
Other issues welcome @stephpenn1 @lilliehaddock 

* LH performance evaluation - SP and BBL need to fill out
* Extended SLA sampling - who, when?
* Data - move from SULI repo to here?
* Background reading
* Further R work?
* U. Delaware visit

**Comment by stephpenn1** [comment]
- Litter script: code structure and data naming
- Lillie next week
- Overall goals for the next 3ish months

**Comment by lilliehaddock** [comment]
Meeting Notes: 
 - SLA paper: Upland and lowland plots, and salinity gradient 
-  need to do a small sample collection at GCREW to quantify if there is a change in SLA seasonally
 - Simplify to sample beech, red maple, sweet gum, black gum
- September 10th U. Delaware

To Do: 
- [ ]  Find a pole pruner (Amazon, Forestry Suppliers, Horticulture sites?)
- [ ]  Assemble a field crew (Kalyn?)
- [ ]  Norbert measurements next week
- [ ] SLA reading
