### ISSUE TITLE
Stephanie - September 2019

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#117]
#### Field Work
- [x] **GRU!** 😢 Work with Licor, and if needed ship back and let's coordinate with Nick to borrow his instrument.
- [x] We want to fill in all missing inventory species before fall _(scheduled 9/13/2019)_
- [ ] Survey and inventory a shore plot for Nate, with BBL _(scheduled 9/13/2019)_
- [x] Repaint plot stakes
- [ ] Install sapflow programs, put new sensors on power _(scheduled 9/5/2019)_
- [ ] Replace bad sapflow sensors
- [x] Fix and relaunch HSLE conductivity meter date issue

#### Coding
- [x] #106 
- [x] Generate Js numbers for Nate
- [x] Create sapflow/Rs analysis Rmarkdown structure
- [ ] #119 

#### Writing
- [x] Assign weekly sapflow paper to BBL
- [x] Finish responses and send to coauthors
- [x] Post responses by 13 September
- [x] Create (very) rough outline of sapflow/Rs paper
- [x] Once Js data pipeline is in place start to explore the data! That midday depression in the JGR manuscript might be a good place to start 

### Recurring tasks
- Litter collection as needed
- Transplant fluxes (every 14-21 days; Lillie)
- Subset fluxes (monthly)
- Assist Lillie w SLA analysis and field work

**Comment by stephpenn1** [comment]
@bpbond Please fill in anything I missed

**Comment by bpbond** [comment]
Looks good; the one big thing missing was Gru. Thanks!
