### ISSUE TITLE
let's think about drake structure

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#123]
I'm working on data processing improvements and `drake.R` keeps getting stuck on our Rmarkdowns. This got me thinking that maybe we want separate _data processing_ from _data analysis_.. it might be cleaner to have:

- one script that runs drake to read in, reformat, and produce data frames ready to be analyzed and distributed
- one script that runs drake to run `proximity_report`, `ts_report`, and maybe `README`

Thoughts?

**Comment by bpbond** [comment]
What do you mean getting stuck? Errors? Or just it takes a long time.

We could split it up...the big disadvantage is that now we've lost the end-to-end part, i.e. can't be sure when we run an analysis that it's using consistent, latest data. (Without running the first part first.) I don't want `drake` to be more trouble than it's worth though.

Would it help to just build specific targets? We could add the following to the end of `drake.R`:
```R
quickplan <- filter(plan, !grepl("rmarkdown", command))
```
...which should let you type `make(quickplan)` to run everything EXCEPT the Rmarkdown files.
