### ISSUE TITLE
SP end of 2019 goals

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#125]
### **October**
- [x] Submit bg-2019-218 manuscript revisions by **Oct 23**

### **November**
- [x] Begin analyzing Rs and Js data by making a table of # of datapoints & available time periods, and prelim plots in Rmarkdown
- [x] Create preliminary time lag plots for AGU poster
- [ ] Develop AGU poster

### **December**
- [ ] Complete rough outline (phrases or sentences) for Rs-Js paper

**Comment by bpbond** [comment]
At some point, late in 2019 or early 2020, probably shut down Stuart and send him in for checking and recalibration?

**Comment by stephpenn1** [comment]
@bpbond Yes, and going along with that.. I'd like to check and maintenance the long term chambers (replace foam seals, gaskets if torn, etc.)

**Comment by bpbond** [comment]
Perfect, agreed. The timing here will mostly be driven by the data needs of your AGU analysis.
