### ISSUE TITLE
bg-2019-218 figure revisions

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#126]
- [x] **Table 1** R1 suggests adding altitude, thoughts? We'd have to look through Gru measurements or estimate
- [x] **Table 2** R1 suggests using parentheses instead of +/-
- [x] **Table 3** Check df values, remove 1 digit (R1 also suggests adding H2 and H3 model tables?)
- [x] **Figure 2** 
       - Caption: remove "mean"
       - Test subsetting high vs. low BA as separate lines
- [x] **Figure 3** Reduce line size and see if this improves visibility of 1-5m distance, R1 also suggested trying a log scale, we can also try zooming in on 1-5 meters 
- [x] **Figure 4** check axes, R1 and R3 think they are flipped 
- [x] **Figure 5** Replace with figure from `relaimpo` package
- [x] All figs: check special characters in axes (especially in figs that show Rs units), ensure all on `theme_bw()` with similar fig dimensions

**Comment by bpbond** [comment]
>R1 suggests adding altitude, thoughts? We'd have to look through Gru measurements or estimate

Easy enough to do. Gru logs bounce around -10 to 20 m asl. I think you could estimate 2-5 for GCREW, 4-10 for Canoe Shed, 6-15 for North Branch.

**Comment by bpbond** [comment]
>- Test subsetting high vs. low BA as separate lines

![Figure3](https://user-images.githubusercontent.com/1956468/67253149-3a06fa00-f444-11e9-9d63-62abe98fd22a.png)

**Comment by bpbond** [comment]
>we can also try zooming in on 1-5 meters

![Figure2](https://user-images.githubusercontent.com/1956468/67253488-d7aef900-f445-11e9-93c2-3d8c50bcb756.png)

**Comment by bpbond** [comment]
Logging the x axis doesn't improve things.

**Comment by bpbond** [comment]
I just realized that all the tables and main results are going to need to be redone, right? Because we now have the data for the last few collar data, that Lillie and I measured?
