### ISSUE TITLE
SALT_20190906_LT.81x needs to be split and uploaded

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#128]
* file send via file transfer 10/28
* note we haven't changed these file names to new plot names, let's do this going forward

**Comment by bpbond** [comment]
I'm using `split_licor_file()` [here](https://github.com/bpbond/cosore/blob/master/R/utils.R) to do this.

**Comment by stephpenn1** [comment]
Thanks, will use this function in the future
