### ISSUE TITLE
HOBO micro stations issues (model H21-USB)

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#129]
Just spoke with HOBO technical support David MacDonald (reference case #00081455 in the future)...

**MSLE** 
It's possible that when the cables got chewed, it created a short that went to the board and damaged it. HOBO does not repair this but said we can try to isolate the short by testing different ports and seeing which one drains battery faster. To me, this seems too time consuming and a waste of valuable data logging time. Our best bet might be to replace... or be more vigilant about the battery life.

**HSLE**
Things to check:
- Battery teminals - look for discoloration, rust, or white residue
- Check for corrosion on the board
- Make sure we are using the most up to date software

HOBO also does not cover repairs of corroded boards, etc. so we would have to replace this station if we can't troubleshoot.

**Comment by bpbond** [comment]
Thank you for making the call. By any chance did you get a price estimate if we need to replace?

**Comment by stephpenn1** [comment]
No, though [website](https://www.onsetcomp.com/products/data-loggers/h21-usb) says $220

**Comment by stephpenn1** [comment]
Micro stations were replaced at HSLE and MSLE 1/24/2020
