### ISSUE TITLE
Stephanie - November 2019

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#133]
#### Field
- [x] litter weekly
- [x] sapflow: check numbers and replace bad sensors

#### Office
- [x] book AGU flights
- [x] finalize AGU hotel
- [x] #119 
- [x] upload sapflow tree info
- [x] order new weather stations #129 
- [x] produce prelim plots for AGU

**Comment by bpbond** [comment]
Litter. We're drowning in it, and need to ask, for what? That is, what data do we _need_ versus only _desire_? Here's one thought:

We need a full year of species-resolved leaf litter data, for Lillie's analysis, as well as probably you/Nate/Wenzhi too. So
- Sort by species (as we've been doing) and weigh all data, transplant + TEMPEST, for 1 October 2018–30 September 2019. This is mostly but not entirely done.

But we don't need to _keep_ all of this. So from those samples, what if we 
- Take a good (big) sample of all the categories, combine into a single banker's box, and toss the rest?

Second, we have the data starting 1 October 2019. Maybe for this, and for now, we just
- Measure woody, repro, and total leaf (i.e. don't do any species separation). That will let us process stuff a LOT faster. 
- Probably toss the samples after processing and QC'ing.

Third, do we still need to collect transplant plot litter? I'm unsure.

**Comment by bpbond** [comment]
- [ ] Do you have time to run the Gru output through SoilFluxPro? It would be great to put eyeballs on these data in advance of AGU.
