### ISSUE TITLE
Tree proximity analysis

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#14]
We expect that soil respiration will be correlated with temperature–this is almost always true, except in extremely water-limited system–and probably with moisture.

One question that might make a good poster (and later paper) would be: is soil respiration rate, or its temp/moisture sensitivity, spatially correlated with nearby trees? See for example

http://dx.doi.org/10.1007/s10533-004-5889-6
http://dx.doi.org/10.1007/s11104-006-9052-0
http://dx.doi.org/10.1016/j.soilbio.2012.04.024

Since the surface CO2 flux is derived overwhelmingly from microbes and plant roots, we might hypothesize that collars closer to more and larger trees will have different flux dynamics than those far away. This would be straightforward to test once we have a dataset documenting, for each collar, distance to nearest trees (e.g. 2 m to tree #X, 3.5 m to tree #Y, etc). And we could use only the control collars for this question.

**Comment by bpbond** [comment]
H1: Collars closer to more trees (tree basal area) near them will have higher fluxes.
H2: Collars closer to more trees will have higher temperature sensitivity. (Mechanism for H1.)
H3: This effect will be limited to leaf-on (growing) season. In dormant season, no effect.
H4: This effect will be stronger in well-watered conditions (downhill, non-drought), because trees dry before soil.

**Comment by bpbond** [comment]
@stephpenn1 Just committed [collar_proximity.csv](https://github.com/PNNL-PREMIS/PREMIS-ghg/blob/master/inventory_data/collar_proximity.csv), which is real proximity data for two GCREW collars (I measured while Licor'ing today).

I think this will be a good data processing exercise! Let's say the first goal is to produce a graph with two lines on it, one for each collar; on the x axis is distance (m) and on the y axis is cumulative number of trees. In other words, it should show the number of trees within 1 m, 2 m, 3 m, etc., with the lines constantly rising.

Can you think about the steps required for this and open a PR, e.g.: 

```R
# 1. Read proximity data
# 2. QA/error check proximity data [what are errors?]
# 3. Read tree inventory data and join by...
# (Etc.)
```

**Comment by stephpenn1** [comment]
Awesome about new dataset! All looks/sounds great. How creepy is it that yesterday I created a new branch also named `tree-proximity-analysis`!

**Comment by stephpenn1** [comment]
Still a bit confused on what data goes on the y axis for this plot: _on the x axis is distance (m) and on the y axis is cumulative number of trees_ ... is this to get a distribution of the trees? Just a sequence of numbers 0-10 on the y axis?

**Comment by bpbond** [comment]
Distance is on _x_, so is 1:10 basically. The _y_ axis is the number of trees within that distance from the collar. So the curves are cumulative: if there is one trees at 1m, and the second at 2m, etc., it'll be a straight line at a 45 degree angle. Does that make sense?

**Comment by bpbond** [comment]
Something like this:
![example](https://user-images.githubusercontent.com/1956468/41386492-895e281a-6f4f-11e8-8568-8aec9379d755.png)

**Comment by stephpenn1** [comment]
![tree_dist](https://user-images.githubusercontent.com/20341158/41429643-3653bf00-6ffd-11e8-97a2-04bdc6ad8a9d.png)

**Comment by stephpenn1** [comment]
Not a fan of the gradient legend color.. working on fixing it

**Comment by bpbond** [comment]
Very nice!

**Comment by bpbond** [comment]
Seems safe to close this.
