### ISSUE TITLE
Because no one ever planned an office holiday party on GitHub before

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#140]
* Theme: @stephpenn1 suggests "Winter Wonderland"
* Budget: $730 (confirmed with NM)
* Catering: check Busboys, Whole Foods, ...?
* Decorations: Do some research Amazon/Target/etc.
* Games: something fairly simple. Not sure yet.

Paulette note: PL: "I thought about our convo on my way home and wanted to make sure that what I was asking about the supplies made sense because I didn’t give the background about catering. So, if you all are thinking of using a caterer, the caterer will give options some times for adding in tablecloths and plates and stuff like that. Sometimes this stuff is included in the cost and sometimes it’s not, so if it’s not included in the cost I can make sure that we have extra on hand, if possible, of what they don’t provide as I have to purchase plates and meeting supplies to replenish what we’re low on or have run out of. My budget is really low, but I can spread things around to make sure that we have stuff. So, I hope that helps and we can talk more next week!"

**Comment by bpbond** [comment]
## Decorations

- [ ] [12PCS Snowflake Winter Wonderland Birthday Decorations](https://www.amazon.com/jollylife-Snowflake-Wonderland-Birthday-Decorations/dp/B075RPYNJF/ref=sxin_0_ac_d_rm) $12
- [ ] [Twinkle Star 300 LED Window Curtain String Light (White)](https://www.amazon.com/Twinkle-Star-Curtain-Christmas-Decoration/dp/B06Y44G3TS/ref=sr_1_2) $16
- [ ] [Sequin Table Runners Gold- 12 By 108 Inch](https://www.amazon.com/ACRABROS-Runner-Gold-Supplies-Decorations-Birthday/dp/B06XBS9DCM/ref=sr_1_4) $10
- [ ] [SHYMERY Flameless Votive Tealight Candles](https://www.amazon.com/Flameless-Flickering-Realistic-Festivals-Decoration/dp/B07HQSBJLJ/ref=sr_1_1) $10
- [ ] [JOYIN 18 Pieces Snowflake Hanging Strings and Hanging Swirls](https://www.amazon.com/JOYIN-Christmas-Decorations-Snowflake-Wonderland/dp/B07JMGSYTG/ref=sr_1_5) $10
- [ ] [Snowflake Swirls Decoration(30pcs)](https://www.amazon.com/Snowflake-Decoration-Konsait-Christmas-Wonderland/dp/B0773LBDJH/ref=sr_1_12) $11

**Comment by bpbond** [comment]
## Table settings


- [ ] [50 Disposable Christmas Cups](https://www.amazon.com/Disposable-Christmas-Scattered-Snowflakes-Supplies/dp/B07DLCKXPL/ref=sr_1_8) $17
- [ ] [Gift Boutique Gold Dot Disposable Paper Plates and Cups Set For 50](https://www.amazon.com/Gift-Boutique-Disposable-Thanksgiving-Christmas/dp/B07BK7H98W/ref=sr_1_11) $20

**Comment by bpbond** [comment]
## Games

- [ ] [Ugly Sweater Contest Ballot Box and 50 Voting Cards](https://www.amazon.com/ORIENTAL-CHERRY-Christmas-Party-Supplies-Decorations-Together/dp/B07Y1BZG7V/ref=sr_1_15) $12

**Comment by bpbond** [comment]
Circular link for posterity: https://twitter.com/_scpenn1/status/1202383660768546818?s=20

**Comment by bpbond** [comment]
Catering menus:
- [ ] [Busboys and Poets](https://www.busboysandpoets.com/menu/catering-menu/) looks good but spendy
- [ ] [Whole Foods](https://www.wholefoodsmarket.com/shop/UMD/3144) super convenient to work
- [ ] [Giant Foods](https://giantfood.com/site/12/0/0/37/6aad5b74-68d4-4427-a4e2-f4c3ae6ae363.pdf) lowest price unsurprisingly

**Comment by stephpenn1** [comment]
Today we ordered:
- Decorations

 Need:
- 3 white tablecloths from Target
- Food (BBL to send out RSVP reminder)
- BBL and SP to make desserts

**Comment by bpbond** [comment]
Ordered our big splurge: 3 x 20-person wrap boxes from Whole Foods, $389

**Comment by bpbond** [comment]
WOO HOO 🎉 

I'm going to give @stephpenn1 the honor of closing this :)
