### ISSUE TITLE
Collect all instrument serial numbers into a single list

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#144]
Useful for record keeping purposes.

**Comment by stephpenn1** [comment]
Done, instrument serial numbers now live [here](https://github.com/PNNL-PREMIS/PREMIS-ghg/blob/master/design/instrument_info.csv). Also note: Norbert does not have a PNNL property tag, do you know if he was originally issued one?

**Comment by bpbond** [comment]
Thank you! No, I don't know. Searched my email and don't see anything about a tag for him.
