### ISSUE TITLE
Proximity report broken

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#148]
Run at updated (ff0dd7b) master:

```R
> make(plan)
target prox_report
Target prox_report messages:
  Quitting from lines 124-136 (proximity_results.Rmd) 
fail prox_report
Error: Target `prox_report` failed. Call `diagnose(prox_report)` for details. Error message:
  unused argument (-Date)
```

It would be good to fix this ASAP since with your paper accepted we want to create a tag for it.

**Comment by stephpenn1** [comment]
https://github.com/PNNL-PREMIS/PREMIS-ghg/commit/a7a8a026dc06c8f6f294b2da5e3bd79a48920b53 

Should be fixed now, could you check on your computer if drake runs?

**Comment by bpbond** [comment]
👍 looks good--thank you! Our NEXT project, let's implement continuous integration, so every single commit gets checked automatically.
