### ISSUE TITLE
Stephanie - March 2020

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#153]
### Coding
- [x] #106 
- [x] #110 
- [ ] #134 
- [ ] Well timestamp

### TEMPEST
- [x] Meet with Roy + Anya to create contingency plan for sensor installation
- [ ] Research IRGA shelters
- [x] Find length of 8150 power cable

### COSORE
- [x] Figure for ESSD paper (https://github.com/bpbond/cosore/issues/173)
- [x] Create pull request
- [x] Email contributors, close survey in 1 week

### Rs/Js
- [ ] Full sentence outline

**Comment by bpbond** [comment]
I'd add

- TEMPEST: work with Anya and Ben to plan IRGA deployment in exclusion plots
