### ISSUE TITLE
Stephanie - May

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#26]
- [x] Email Pat about GC at SERC
- [ ] Figure out long-term chamber set-up
- [x] Continue taking measurements at SERC (how often are we hoping, @bpbond? weekly?)
- [ ] Make error plot more clear

**Comment by bpbond** [comment]
More or less weekly, yes, but if it takes 2 full days then every 10 days OK I think.

Other things:
- [ ] Help Nate and Charlotte get set up, learn about downloading their data
- [ ] When weather stations arrive, organize and plan installation
- [ ] Read and discuss a paper (I'll provide) on soil respiration and distance-to-trees

**Comment by bpbond** [comment]
Looking ahead to the week of May 29-June 1, I'll be out of the office, but hopefully you will be in! I think big priorities are 
- [ ] Downloading and processing last two weeks' data
- [ ] If you feel good, getting Nate and Charlotte's data downloaded and sent so they can look at it
- [ ] Practice downloading the weather station we set up. Take a look at the data
- [ ] Getting the other two weather stations set up, like we did ten days ago with the first, so they're ready to be installed in the field the week of June 4
- [ ] Coding - issue #32

**Comment by stephpenn1** [comment]
Note: unchecked items moved to June checklist
