### ISSUE TITLE
Restructure dat and plot scripts

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#29]
`licordat.R` will read all Licor files; read and merge the plot/collar metadata (i.e. lines 18-47 in current plot script); and save the resulting data frame `readr::write_csv(dat, "outputs/licordat.csv")`. This provides a single data frame any subsequent script can quickly read and work on.

`licorplot.R` now gets much simpler--just read the data file above and start plotting.
* Read data file
* Plot CV (N=2) of measurements at each collar - identify large variations between the two we're making - plot over time
* Plot CV (N=4 or 8 for control) of _treatments_ - e.g. all HSLE->HSHE - identify large variations - plot over time

**Comment by stephpenn1** [comment]
![cv_btwn_obs](https://user-images.githubusercontent.com/20341158/40795601-140ad796-64f2-11e8-84bc-283cf57a5513.png)

**Comment by stephpenn1** [comment]
![ggcv_btwn_exp](https://user-images.githubusercontent.com/20341158/40795674-4f9ffcd2-64f2-11e8-9eee-aa5ed930fd8b.png)

(Not sure why the key is zoomed in)

**Comment by bpbond** [comment]
Seems like this can be closed?

**Comment by stephpenn1** [comment]
Yep, as long as the plots look good to you
