### ISSUE TITLE
Do we need the extra control collars?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#32]
Hi @stephpenn1 - since we've dropped, for now, the four "trenched" treatments at five plots (HSLE, HSME, and HSHE at GCREW; MSLE at Canoe Shed; and LELE at North Branch), we've been measuring those four as extra controls. But this adds a fair amount of time (as I realized on Friday), and it would be good to know if they're giving us extra useful information or not. Or we should measure them only occasionally.

At your convenience, can you graph, for each plot, a mean line and error bars (s.d.) for the 8 controls, and overlaying it another line and error bars for the four 'true' controls. In other words, this will involve (i) filtering for the eight controls at each plot and computing a mean and s.d.; (ii) filtering for the four true controls and doing the same; (iii) combining these into a single data frame; (iv) graphing, with color = (all controls or true controls) and faceting by plot.

Thanks!

**Comment by stephpenn1** [comment]
![controls](https://user-images.githubusercontent.com/20341158/41177674-7a8fdd5a-6b54-11e8-9385-f76de710f6be.png)

**Comment by bpbond** [comment]
Wow, interesting. Thank you! The answer seems to be pretty clearly "no". I skipped the LSLE 'extra' controls today, actually, because I was running out of time. For now, let's say that they should only be measured occasionally--say once every six weeks? Normally, feel free to skip them, while being sure to measure the true controls. Sound good?
