### ISSUE TITLE
Stephanie - June

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#38]
- [ ] Download sapflow data ~ every 2 weeks, send to Nate and Charlotte
- [ ] Continue taking flux measurements, trying for every 7-10 days if possible. Can skip the "extra" controls every other time, pending #32 
- [ ] Record chamber offset values and upload as CSV
- [x] Work with Nate on leaf water potentials and Turgor loss curves
- [ ] Figure out long-term chamber set-up
- [x] Make error plot/error bars more clear
- [x] Read and discuss a paper (@bpbond will provide) on soil respiration and distance-to-trees
- [ ] Measure, for each control collar, distance to nearest trees (e.g. within 10m) for #14 
- [x] Come up with goals/plan for Beaver Creek trip (@bpbond would this be useful?)

**Comment by bpbond** [comment]
>Come up with goals/plan for Beaver Creek trip

Useful but I'm already on this one. Let me nail down a couple things and then we can go over the plan next week. Thanks!
