### ISSUE TITLE
Stephanie - October

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#54]
**Fieldwork**
- [ ] Record tree-distance-to-collar data, following [existing data format](https://github.com/PNNL-PREMIS/PREMIS-ghg/blob/master/inventory_data/collar_proximity.csv) for #14 
- [ ] We probably need to do a little maintenance on Norbert–at the very least, 'zero' his IRGA. Talk to Pat about how they do this and whether we can use. (Hopefully tank of CO2 + scrub + desiccant setup.)
- [x] Licor measurements every ~7-10~ 10-14 days
- [x] Collect leaf litter every 2 weeks, dry, sort (we will discuss, but at the very least leaf vs. non-leaf), weigh
- [ ] Install field cameras
- [x] Download eosense instruments, pack, return to company
- [ ] Measure (w/ @bpbond ) James's test plot collars and perhaps leaf porometry

**Writing**
- [x] Create full sentence outline for tree proximity paper - each paragraph should have 2-4 secondary points after the topic sentence
- [ ] Add citations to intro paragraph
- [ ] Work on methods section

**Coding/office**
- [x] ForC mapping  <--- top priority for early October
- [ ] Tree-distance analysis, figures
- [x] Organize 1207
- [ ] Get wx data (precip, global radiation, VPD, PAR parameters) for use in Baseliner/sapflow
- [x] Send eosenses back by October 5th (Friday)
- [ ] Be available for consultation/help for high school interns (Rebecca and Izzy) who will be starting mid-October probably

@bpbond feel free to add anything you think of

**Comment by bpbond** [comment]
Made some changes and added some detail.
