### ISSUE TITLE
Tree 521 at Canoe Shed - species?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#59]
This is the Princess Tree (perhaps) or Catalpa. Need to resolve.

**Comment by bpbond** [comment]
Catalpa flowers are white; Paulownia flowers are described as lavender, purple or violet. 
Catalpa leaves occur in whorls of three. Paulownia is opposite.

@stephpenn1 do you remember flower colors?

**Comment by stephpenn1** [comment]
No, I never saw any flowers. The top (canopy?) of the tree is really bare. Most of the leaves were closer to the ground. Let me look back in my photos to see leaf patterns
