### ISSUE TITLE
Missing tree species?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#62]
Hi @stephpenn1 currently in `inventory_data.csv` there are still hundreds of missing tree species. I thought we finished up all the inventory that day with Kalyn? Am I misremembering? Do you have those data on paper? Thanks.

**Comment by stephpenn1** [comment]
Hm, I thought so. I believe you and/or Kalyn had the clipboard.. I didn't do any recording that day.

**Comment by bpbond** [comment]
Eek! OK thanks.
