### ISSUE TITLE
Stephanie - April

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#8]
- [x] Licor processing code should read directory of files, produce graphs of time vs. flux by collar, treatment, site, etc.
- [x] Increase use of PRs for code review.
- [x] Get Licor unit test up and start testing.
- [x] Work with me to develop Licor sampling protocol.
- [ ] Start Licor measurements.  BBL needs to talk w/ PG about calibration gas availability at SERC.
- [x] Prioritize next steps at SERC: elevation transplants, control collars, inventory.
- [ ] Continue to work with MH and me to increase familiarity with SRDB.
- [ ] ERL analysis (#7 ) - BBL needs to set up call.
- [x] Improve read me with short project summary (1-2 paragraphs) from proposal.

**Comment by bpbond** [comment]
This week: create a test data frame with `Timestamp`, `Flux`, and `Collar` (with collar numbers 1-xx); load the `collar_core.csv` and merge together, so every flux observation has all associated data; and then plot up, for example different panels for each plot and a line per collar.

**Comment by bpbond** [comment]
@stephpenn1 Some suggested plots to implement in your script:

Time versus flux, faceted by salinity versus elevation, one line per collar, colored by source plot.
Time versus flux, faceted by salinity versus elevation, one line per source plot, with error bars showing core-to-core s.d.
Temperature versus flux, all data together for now, with a regression line overlaid.

**Comment by bpbond** [comment]
It would great to evaluate whether we need 3 versus 2 Licor measurements. To do this, it would be great to have a figure and/or table with CV (standard deviation divided by the mean) of collar measurements, by date and collar number.

E.g. if the Licor measures fluxes of 1, 2, and 3, the CV is 0.5 or 50%.

**Comment by stephpenn1** [comment]
I did something like this:
    **cv <- dat %>% group_by(month, day, Collar) %>% 
                 summarise(CV = sd(Flux)/mean(Flux))**
![cv](https://user-images.githubusercontent.com/20341158/39008341-eb3608c4-43f7-11e8-845f-008b7e56d4c0.png)

**Comment by bpbond** [comment]
Nice! Yes. Maybe do something like `ggplot(cv, aes(Collar, CV)) + geom_point()` though? A line plot doesn't make much sense in this case.

**Comment by bpbond** [comment]
Let's make that one of our standard diagnostics--i.e. the script should save a plot with this information.

**Comment by stephpenn1** [comment]
![cv_2](https://user-images.githubusercontent.com/20341158/39008659-d43317e2-43f8-11e8-9ad9-94765a190776.png)

**Comment by bpbond** [comment]
Nice! Well, it tells me that generally there's ~5% variability between the three measurements, but sometimes this goes up to 10-20%, and very occasionally much higher.

Can you add color to indicate number of measurements please? E.g.

cv <- dat %>% group_by(month, day, Collar) %>%
summarise(CV = sd(Flux)/mean(Flux), n = n())

**Comment by bpbond** [comment]
...It seems like dropping from 3 to 2 shouldn't be a problem, as long as we keep an eye out for the occasional highly-variable collar, and re-measure if that occurs?

**Comment by stephpenn1** [comment]
![cv_3](https://user-images.githubusercontent.com/20341158/39011389-cf7c022e-4400-11e8-949e-c8917c4610e1.png)

**Comment by stephpenn1** [comment]
Are you saying if we see there is a jump in the flux value between the 2 measurements at a collar, to re-measure?

**Comment by bpbond** [comment]
If that's going to be a hassle, no worries, we don't have to do it. The preliminary data above make a good case that we can go to 2 measurements I think. I wonder what the CV would be if we only use 2...hmm.
