### ISSUE TITLE
Chamber 8 temperature is miswired

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#82]
![port8](https://user-images.githubusercontent.com/1956468/53006553-6aa11a80-3403-11e9-9e21-3c3edefb009e.png)

The temperature data are in V1 instead of V3.

**Comment by bpbond** [comment]
I have put in code to catch this but we want to check when at GCREW.

**Comment by stephpenn1** [comment]
Ah, okay. Thanks for catching that.

**Comment by bpbond** [comment]
This was fixed 2019-03-11.
