### ISSUE TITLE
Port 8 T5 broken or miswired?

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#92]
![T5](https://user-images.githubusercontent.com/1956468/54878726-05c45000-4e07-11e9-9b77-2de2f3d41a8e.png)

**Comment by stephpenn1** [comment]
Oh, sorry I switched the ports so that they match 1-7.

**Comment by bpbond** [comment]
See #82

**Comment by bpbond** [comment]
This was fixed 2019-03-11.
