### ISSUE TITLE
Stephanie - April 2019

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#96]
### Manuscript
- [x] Outline and then write discussion
- [X] Make changes to manuscript as necessary once co-authors add comments
- [x] Finalize figures and check numbers
- [ ] Double space, check all references updated
- [x] Circulate final draft for comment (goal by 2019-04-19)
- [ ] Incorporate co-authors' final comments
- [x] Enter into Information Release
- [ ] Merge `proximity-model` into `master` and create a tag
- [ ] SUBMIT!!! ( ͡° ͜ʖ ͡°) 

### Field Work
- [x] Attach trace gas sampling kit to Norbert
- [ ] Start Methane measurements
- [ ] Sort rest of litter with BBL
- [x] Help Nick (April 27- April 29), Aditi (April 27-May 2), Nate (May 2), and James (date TDB) as needed during SERC visits
- [x] SCP is out Thursday 5/2, Friday 5/3, and Monday 5/6
- [x] Protect weather station sensors?
- [x] Update ~HS and~ MS inventory data at 1-year mark (LS in May)
- [ ] Finish up #58 !!

### Coding
- [ ] ~Fix real-time data~. BBL screwed this up -> #89 
- [ ] Script to handle litter data
- [ ] Jazz 🎵  up sapflow script
- [ ] Write up Baseliner protocol

### Office & misc.
- [x] Talk to Kayla and Chris about May UMBS trip and book it

**Comment by bpbond** [comment]
Made a few changes :)

**Comment by bpbond** [comment]
- [ ] Make a list of remaining prox measurements
