### ISSUE TITLE
Lillie

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#98]
- [x] Check with Pat about a researcher pass for her
- [x] Check with Nate/Vanessa about canopy access tower
- [x] Talk to Jess about crossbow or other high-canopy sampling
- [x] Buy supplies for SLA work: coin envelopes, scanner (unless there's one at SERC? -> Emily used one for water potential leaves' SLA so probably), a long pruner of some sort, clippers
- [x] Investigate R packages to read images and count black pixels

- [x] Think about R tutorial/best way to start her in this. (Rebecca's links? SP will try to find what resources Corinne gave me when I started with R)

**Comment by stephpenn1** [comment]
[Bond-Lamberty-FY17_bbl.docx](https://github.com/PNNL-PREMIS/PREMIS-ghg/files/3056248/Bond-Lamberty-FY17_bbl.docx)
This is the paperwork you sent me as an overview of PREMIS; maybe not this exact document, but some sort of background on the project might be beneficial?

**Comment by bpbond** [comment]
Ah good idea, yes, thanks!

**Comment by stephpenn1** [comment]
Career resources:
- https://careers.umd.edu/students/resumes-cover-letters/resume-tips
- some student society memberships (I know AMS does) provide free resume reviews through an online service
- job postings through AGU, ESWN

**Comment by stephpenn1** [comment]
SLA resources (havn't gone through these yet but to be looked at):
- http://www.nucleodiversus.org/uploads/file/Caracteres%20handbook/Specific%20leaf%20area.pdf
- https://doi.org/10.1046/j.1365-2435.1998.00274.x
- https://doi.org/10.1016/j.agrformet.2011.02.007
- https://www.sciencedirect.com/science/article/pii/S0168192312002766

**Comment by stephpenn1** [comment]
Before May 28 (Lillie start date)
- [ ] Rough outline of summer
- [ ] Send her a **few** documents on background material
- [ ] Get SLA supplies
